# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c_un.ui'
#
# Created: Thu May 13 16:40:36 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(QtGui.QWidget):

   
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1061, 750)
        Form.setMinimumSize(QtCore.QSize(1015, 750))
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(660, 60, 231, 191))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_6.setGeometry(QtCore.QRect(40, 150, 191, 19))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 30, 191, 19))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_4.setGeometry(QtCore.QRect(40, 90, 191, 19))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_3.setGeometry(QtCore.QRect(40, 60, 191, 19))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_5.setGeometry(QtCore.QRect(40, 120, 191, 19))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 60, 631, 101))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox = QtGui.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(80, 30, 81, 31))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(200, 70, 71, 19))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.comboBox_11 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_11.setEnabled(False)
        self.comboBox_11.setGeometry(QtCore.QRect(200, 30, 71, 31))
        self.comboBox_11.setObjectName("comboBox_11")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 160, 631, 181))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(-110, 80, 61, 31))
        self.label_3.setObjectName("label_3")
        self.comboBox_10 = QtGui.QComboBox(self.groupBox)
        self.comboBox_10.setEnabled(False)
        self.comboBox_10.setGeometry(QtCore.QRect(50, 120, 121, 22))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_10.setFont(font)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem(QtCore.QString())
        self.comboBox_3 = QtGui.QComboBox(self.groupBox)
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setGeometry(QtCore.QRect(50, 80, 121, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem(QtCore.QString())
        self.comboBox_3.addItem(QtCore.QString())
        self.comboBox_3.addItem(QtCore.QString())
        self.comboBox_3.addItem(QtCore.QString())
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 30, 221, 22))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem(QtCore.QString())
        self.comboBox_2.addItem(QtCore.QString())
        self.comboBox_2.addItem(QtCore.QString())
        self.comboBox_2.addItem(QtCore.QString())
        self.comboBox_2.addItem(QtCore.QString())
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(280, 70, 71, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 340, 631, 351))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_9 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_9.setEnabled(False)
        self.comboBox_9.setGeometry(QtCore.QRect(320, 260, 51, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_9.setFont(font)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem(QtCore.QString())
        self.comboBox_9.addItem(QtCore.QString())
        self.comboBox_9.addItem(QtCore.QString())
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setEnabled(False)
        self.label_11.setGeometry(QtCore.QRect(30, 260, 46, 14))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QtCore.QRect(210, 260, 31, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_5.setEnabled(False)
        self.comboBox_5.setGeometry(QtCore.QRect(60, 300, 211, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem(QtCore.QString())
        self.comboBox_5.addItem(QtCore.QString())
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_4.setGeometry(QtCore.QRect(50, 130, 211, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem(QtCore.QString())
        self.comboBox_4.addItem(QtCore.QString())
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(200, 90, 46, 14))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_6.setGeometry(QtCore.QRect(300, 90, 71, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem(QtCore.QString())
        self.comboBox_6.addItem(QtCore.QString())
        self.comboBox_6.addItem(QtCore.QString())
        self.comboBox_6.addItem(QtCore.QString())
        self.comboBox_6.addItem(QtCore.QString())
        self.comboBox_6.addItem(QtCore.QString())
        self.comboBox_6.addItem(QtCore.QString())
        self.comboBox_6.addItem(QtCore.QString())

        
        self.comboBox_7 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_7.setGeometry(QtCore.QRect(160, 90, 31, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem(QtCore.QString())
        self.comboBox_7.addItem(QtCore.QString())
        self.comboBox_8 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_8.setEnabled(False)
        self.comboBox_8.setGeometry(QtCore.QRect(160, 260, 31, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem(QtCore.QString())
        self.comboBox_8.addItem(QtCore.QString())
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(30, 50, 121, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(50, 90, 46, 14))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtGui.QFrame(self.groupBox_3)
        self.line.setGeometry(QtCore.QRect(10, 220, 331, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.groupBox_3)
        self.line_2.setGeometry(QtCore.QRect(10, 170, 341, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(70, 210, 151, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(220, 210, 131, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 90, 71, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 90, 61, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(30, 180, 51, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(90, 260, 71, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 260, 71, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(460, 150, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_7.setEnabled(False)
        self.lineEdit_7.setGeometry(QtCore.QRect(430, 260, 51, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.comboBox_13 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_13.setEnabled(False)
        self.comboBox_13.setGeometry(QtCore.QRect(380, 260, 51, 22))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.comboBox_13.setFont(font)
        self.comboBox_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox_13.setFrame(True)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem(QtCore.QString())
        self.comboBox_13.addItem(QtCore.QString())
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(550, 260, 61, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setEnabled(False)
        self.label_13.setGeometry(QtCore.QRect(520, 260, 21, 16))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Рассчет Т.Д. Функции :", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("Form", "А энергия Гиббса-Гельмгольдца", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Form", "S энтропия", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("Form", "U внутренняя энергия", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Form", "H энтальпия", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("Form", "G энергия Гиббса", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Вещество (смесь)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Form", "NH3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Form", "N2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Form", "NO2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("Form", "SO2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("Form", "O2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("Form", "CF2CLH", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("Form", "CF2CL2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(8, QtGui.QApplication.translate("Form", "CH4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(9, QtGui.QApplication.translate("Form", "C2H6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(10, QtGui.QApplication.translate("Form", "C3H8", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Form", "вкл", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Что происходит", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Условия", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_10.setItemText(0, QtGui.QApplication.translate("Form", "Равновесный", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("Form", "Изотерма(T-const)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("Form", "Изобара (P-const)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(2, QtGui.QApplication.translate("Form", "Изохора (V-const)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(3, QtGui.QApplication.translate("Form", "Адиабатно (S-const ??????)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("Form", "--(просто рассчитать ТД ф-цию)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("Form", "Расширение", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("Form", "Сжатие", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(3, QtGui.QApplication.translate("Form", "Охлаждение", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(4, QtGui.QApplication.translate("Form", "Нагревание", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "+СТУПЕНИ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Данные (пустой параметр ищется)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(0, QtGui.QApplication.translate("Form", "кПа", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(1, QtGui.QApplication.translate("Form", "Бар", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(2, QtGui.QApplication.translate("Form", "Атм", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Тконечн=", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Pкон=", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(0, QtGui.QApplication.translate("Form", "Не идеальный (Боголюбов-Майер)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(1, QtGui.QApplication.translate("Form", "Идеальный (Клаперон-Менделеев)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(0, QtGui.QApplication.translate("Form", "Идеальный (Клаперон -Менделеев)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(1, QtGui.QApplication.translate("Form", "Не идеальный (Боголюбов-Маер)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Pнач=", None, QtGui.QApplication.UnicodeUTF8))

        self.comboBox_6.setItemText(0, QtGui.QApplication.translate("Form", "Па", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(1, QtGui.QApplication.translate("Form", "кПа", None, QtGui.QApplication.UnicodeUTF8))        
        self.comboBox_6.setItemText(2, QtGui.QApplication.translate("Form", "Бар", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(3, QtGui.QApplication.translate("Form", "Атм", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(4, QtGui.QApplication.translate("self", "Ат", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(5, QtGui.QApplication.translate("self", "мм рт. ст.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(6, QtGui.QApplication.translate("self", "мм вод. ст.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(7, QtGui.QApplication.translate("self", "psi", None, QtGui.QApplication.UnicodeUTF8))

        self.comboBox_7.setItemText(0, QtGui.QApplication.translate("Form", "К", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(1, QtGui.QApplication.translate("Form", "С", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(0, QtGui.QApplication.translate("Form", "К", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(1, QtGui.QApplication.translate("Form", "С", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Начальные условия:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Конечные условия :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Тнач=", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "колличестов ступеней=1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "+еще всякая ерунда", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Ступени", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Рассчитать", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_13.setItemText(0, QtGui.QApplication.translate("Form", "ρ ид", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_13.setItemText(1, QtGui.QApplication.translate("Form", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "V=", None, QtGui.QApplication.UnicodeUTF8))
	self.connect(self.pushButton, QtCore.SIGNAL('clicked()'), self.vhodiashie_vozmuhenia)
#+++++++
#        self.connect(self.pushButton, QtCore.SIGNAL('clicked()'), self.kyky)
#
	
